# Site settings
title: Barbara's Profile
email: barb.donnini@gmial.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/patchwork-gh-pages-24"
url: "http://bdonnini9055.github.io"
twitter_username: barb.donnini
github_username:  bdonnini9055
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
